#!/bin/bash

if [ "$CURRENT_PATH" = "" ]; then
   CURDIR=`pwd`
   CURRENT_PATH=${CURDIR%/cdk}
   export PATH=/usr/sbin:/sbin:$PATH
   CONFIGPARAM=`cat lastChoice`
   echo
   echo "Performing autogen.sh..."
   echo "------------------------"
   ./autogen.sh
   echo
   echo "Performing configure..."
   echo "-----------------------"
   echo
   ./configure $CONFIGPARAM
fi

