#!/bin/sh
#Version 150907.1

echo "Fortis HS8200 Neutrino"

MODDIR=/lib/modules

echo "Init frontpanel"
insmod $MODDIR/nuvoton.ko
insmod $MODDIR/simu_button.ko

if [ -e /var/etc/.firstboot ]; then
   echo "Wait 1 min." > /dev/vfd
   echo "WAIT 1 minute"
   rm /var/etc/.firstboot
   sleep 1
   touch /dev/.devfsd
else
   echo "Load 10" > /dev/vfd
   echo "Start (LOAD 10)"
fi

if [ -d /dev/sda1/Recordings ]; then
   fsck.jfs -a /dev/sda1
fi

/etc/init.d/mountvirtfs start
/etc/init.d/portmap start

insmod $MODDIR/e2_proc.ko
#insmod $MODDIR/sata.ko

# Start automounter with umount timeout of 5 seconds
if [ -e /etc/init.d/automount ]; then
   /usr/sbin/automount --timeout=5 /autofs file /etc/auto.usb
fi

echo "Starting DEBUG Interface"
/etc/init.d/mountall start
/etc/init.d/hostname start

echo -n "Starting telnetd "
/usr/sbin/telnetd -l /bin/autologin
echo "with autologin"

echo "Init stmfb (LOAD 9)"
echo "Load 9" > /dev/vfd
insmod $MODDIR/stmcore-display-sti7105.ko
insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:rgb:rgb # display1=720x576-16@50:1m:pal:cvbs;

echo "Loading modules"

if [ ! -e /lib/firmware/audio.elf ] || [ ! -e /lib/firmware/video.elf ]; then
  echo "FIRMWARE MISSING!"
  echo "FW MISSING!" > /dev/vfd
fi

echo "Load audio firmware (LOAD 8)"
echo "Load 8" > /dev/vfd
/bin/dd if=/dev/zero of=/dev/st231-1 bs=1024 count=4096
/bin/ustslave /dev/st231-1 /lib/firmware/audio.elf > /dev/null

echo "Load video firmware (LOAD 7)"
echo "Load 7" > /dev/vfd
/bin/dd if=/dev/zero of=/dev/st231-0 bs=1024 count=4096
/bin/ustslave /dev/st231-0 /lib/firmware/video.elf > /dev/null

echo "Init embx (LOAD 6)"
echo "Load 6" > /dev/vfd
insmod $MODDIR/embxshell.ko
insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0
insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000
insmod $MODDIR/mme_host.ko transport0=shm

echo "Init AVS (LOAD 5)"
echo "Load 5" > /dev/vfd
insmod $MODDIR/avs.ko type=stv6418

player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
echo "Init player $player (LOAD 4)"
echo "Load 4" > /dev/vfd

insmod $MODDIR/mmelog.ko
insmod $MODDIR/ksound.ko
insmod $MODDIR/p2div64.ko
insmod $MODDIR/stm_v4l2.ko
insmod $MODDIR/stmvout.ko
insmod $MODDIR/stmvbi.ko
insmod $MODDIR/pseudocard.ko

insmod $MODDIR/frontend_platform.ko
insmod $MODDIR/socket.ko
insmod $MODDIR/lnbh221.ko
insmod $MODDIR/lnb_pio.ko
# DVB-S
insmod $MODDIR/avl2108.ko
# DVB-C
#insmod $MODDIR/tda10024.ko
# DVB-T
#insmod $MODDIR/cxd2820.ko

insmod $MODDIR/starci.ko
insmod $MODDIR/smartcard.ko

#pti_arg="waitMS=20 videoMem=4096"
#echo "Full feature pti"
pti_arg=""
echo "Simple pti"
insmod $MODDIR/pti.ko $pti_arg
insmod $MODDIR/stm_monitor.ko
insmod $MODDIR/stmsysfs.ko
insmod $MODDIR/stmdvb.ko

echo "Init player2 (LOAD 3)"
echo "Load 3" > /dev/vfd
insmod $MODDIR/player2.ko discardlateframe=0
insmod $MODDIR/sth264pp.ko
insmod $MODDIR/stmalloc.ko
insmod $MODDIR/platform.ko
insmod $MODDIR/silencegen.ko
insmod $MODDIR/bpamem.ko

echo "Init HDMI-CEC"
if [ -e $MODDIR/cec.ko ];then
   insmod $MODDIR/cec.ko activemode=1
fi

#if [ -e /boot/neutrinologo.mvi ]; then
#   showiframe -p /boot/neutrinologo.mvi &
#fi
#stfbcontrol a 0

echo "Init rc (LOAD 2)"
echo "Load 2" > /dev/vfd
/bin/evremote2 10 120 &

# Load modules from /var/etc/modules.extra
[ -f /var/etc/modules.extra ] && eval `sed -e 's/#.*//' -e '/^\s*$/d' -e 's/^\(.*\)/insmod \0;/' < /var/etc/modules.extra`

#stfbcontrol a 255

#timefix
date -s "201509011200"

#wlan=rtl8188cu
if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
   echo "No WLAN"
else
   insmod $MODDIR/$wlan.ko
   echo "$wlan WLAN"
#   echo "$wlan WLAN" > /dev/vfd
#   sleep 3
fi

if [ -e $MODDIR/ntfs.ko ]; then
   insmod $MODDIR/ntfs.ko
fi

if [ -e $MODDIR/cifs.ko ]; then
   insmod $MODDIR/cifs.ko
fi

echo "Init FTP (LOAD 1)"
echo "Load 1" > /dev/vfd
/etc/init.d/vsftpd start
/usr/sbin/inetd

NFS=`grep -c nfs /proc/cmdline`
if [ "$NFS" -eq "1" ]; then
   echo "Booting from nfs, don't set network"
else
   if [ -e /etc/network/interfaces ]; then
      ip addr flush eth0
      /etc/init.d/networking stop
      DHCP=`grep -c 'iface eth0 inet dhcp' /etc/network/interfaces`
      if [ "$DHCP" -eq "1" ]; then
         echo "Starting DHCP on eth0"
         /etc/init.d/udhcpc start
      fi
      /etc/init.d/networking start
   fi
fi

echo "Start Neutrino"
echo "Start Neutrino" > /dev/vfd

until false
do
   echo "Starting neutrino ->"
   /usr/local/bin/neutrino
   rtv=$?
   echo "neutrino ended <- RTV: " $rtv
   case "$rtv" in
      0) echo "0"
         echo "SHUTDOWN"
         echo "Shutdown" > /dev/vfd
         if [ -e /usr/local/share/enigma2/shutdown.mvi ]; then
            showiframe -p /usr/local/share/enigma2/shutdown.mvi &
         fi
         init 0;;
      1) echo "1"
         echo "REBOOT"
         echo "Reboot" > /dev/vfd
         init 6;;
      *) echo "*"
         echo "ERROR"
         echo "Error" > /dev/vfd
         init 6;;
   esac
done

#never reached
echo "REBOOT HS8200" > /dev/vfd
echo "REBOOT HS8200"
init 6
