#!/bin/sh
#Version 160116.1

echo "Fortis FS9000/9200 Enigma2"

MODDIR=/lib/modules

insmod $MODDIR/e2_proc.ko

if [ ! -e /dev/vfd ]; then
    mknod -m 0660 /dev/vfd c 147 0
fi
echo "Init frontpanel"
insmod $MODDIR/nuvoton.ko

if [ -e /var/etc/.firstboot ]; then
   echo "Wait 1 min." > /dev/vfd
   echo "WAIT 1 min"
   rm /var/etc/.firstboot
   touch /dev/.devfsd
else
   echo "Load 10" > /dev/vfd
   echo "LOAD 10"
fi

/etc/init.d/mountvirtfs start

echo "Starting DEBUG Interface"
/etc/init.d/mountall start
/etc/init.d/hostname start

echo -n "Starting telnetd "
autologin=`cat /etc/enigma2/settings | grep systemoptions.autologin | cut -d "=" -f2`
if [ ! $autologin ]; then
   /usr/sbin/telnetd -l /bin/autologin
   echo "with autologin"
else
   /usr/sbin/telnetd -l /bin/login
   echo "with normal login"
fi

echo "Init stmfb (LOAD 9)"
echo "Load 9" > /dev/vfd
insmod $MODDIR/stmcore-display-stx7109c3.ko
if grep -q "config.av.videoport=Scart" /etc/enigma2/settings; then
  insmod $MODDIR/stmfb.ko display0=720x576-32@50:15m:pal:rgb:rgb #SCART
else
  insmod $MODDIR/stmfb.ko display0=1280x720-32@50:16m:pal:rgb:rgb; #HDMI
fi

echo "Loading modules"
  
if [ ! -e /boot/audio.elf ] || [ ! -e /boot/video.elf ]; then
   echo "FIRMWARE MISSING!"
   echo "FW MISSING!" > /dev/vfd
fi

echo "Load audio firmware (LOAD 8)"
echo "Load 8" > /dev/vfd
/bin/ustslave /dev/st231-1 /boot/audio.elf > /dev/null

echo "Load video firmware (LOAD 7)"
echo "Load 7" > /dev/vfd
/bin/ustslave /dev/st231-0 /boot/video.elf > /dev/null

echo "Init embx (LOAD 6)"
echo "Load 6" > /dev/vfd
insmod $MODDIR/embxshell.ko
insmod $MODDIR/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:0 ;
insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:1024:0xa4000000:0x10000000 ;
insmod $MODDIR/mme_host.ko transport0=shm

echo "Init AVS (LOAD 5)"
echo "Load 5" > /dev/vfd
insmod $MODDIR/avs.ko type=stv6412

player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
echo "Init player $player (LOAD 4)"
echo "Load 4" > /dev/vfd

insmod $MODDIR/mmelog.ko
insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER1;
insmod $MODDIR/ksound.ko
insmod $MODDIR/p2div64.ko
insmod $MODDIR/stm_v4l2.ko
insmod $MODDIR/pseudocard.ko

insmod $MODDIR/stv090x.ko
insmod $MODDIR/starci.ko

if [ $player=='player179' ] || [ $player=='player191' ]; then
   # Full feature pti
#   insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
#   if [ $?=='2' ]; then
      # Simple pti
      insmod $MODDIR/pti.ko
#   fi
   insmod $MODDIR/stm_monitor.ko
   insmod $MODDIR/stmsysfs.ko
   insmod $MODDIR/stmdvb.ko
#   insmod $MODDIR/stmdvb.ko
else
   insmod $MODDIR/pti.ko
   insmod $MODDIR/stmdvb.ko
   insmod $MODDIR/stm_monitor.ko
fi

echo "Init player2 (LOAD 3)"
echo "Load 3" > /dev/vfd
insmod $MODDIR/player2.ko noaudiosync=1; discardlateframe=0; useoldaudiofw=1;
insmod $MODDIR/sth264pp.ko
insmod $MODDIR/stmalloc.ko
insmod $MODDIR/platform.ko

if [ -e /boot/bootlogo.mvi ]; then
   showiframe -p /boot/bootlogo.mvi &
fi

insmod $MODDIR/boxtype.ko
insmod $MODDIR/simu_button.ko

echo "Init lircd (LOAD 2)"
echo "Load 2" > /dev/vfd
mknod /dev/rc c 147 1

/bin/evremote2 10 140 &

echo "Init smartcard cardreader"
mknod /dev/sci0 c 253 0
mknod /dev/sci1 c 253 1
#insmod $MODDIR/sci-ng.ko

wlan=`cat /etc/enigma2/settings | grep systemoptions.wlan | cut -d "=" -f2`
if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
   echo "No WLAN"
else
   insmod $MODDIR/$wlan.ko
   echo "$wlan WLAN"
#   echo "$wlan WLAN" > /dev/vfd
#   sleep 3
fi

if [ -e $MODDIR/ntfs.ko ]; then
   insmod $MODDIR/ntfs.ko
fi

if [ -e $MODDIR/cifs.ko ]; then
   insmod $MODDIR/cifs.ko
fi

echo "Init FTP (LOAD 1)"
echo "Load 1" > /dev/vfd
/etc/init.d/portmap start
/etc/init.d/vsftpd start
/usr/sbin/inetd

NFS=`grep -c nfs /proc/cmdline`
if [ "$NFS" -eq "1" ]; then
   echo "Booting from nfs, don't set network"
else
   if [ -e /etc/network/interfaces ]; then
      ip addr flush eth0
      /etc/init.d/networking stop
      DHCP=`grep -c 'iface eth0 inet dhcp' /etc/network/interfaces`
      if [ "$DHCP" -eq "1" ]; then
         echo "Starting DHCP on eth0"
         /etc/init.d/udhcpc start
      fi
      /etc/init.d/networking start &
   fi
fi
#Allow network to wake up and initialize
sleep 2
#Show IP address on frontpanel
#ip=`ifconfig eth0 | sed -n '/inet addr/s/.*addr.\([^ ]*\) .*/\1/p'`
#echo "IP $ip" > /dev/vfd
#sleep 3

# Start automount
if [ -e /etc/init.d/automount ]; then
   python /etc/init.d/automount &
fi

# Do own extras
if [ -e /etc/ownscript.sh ]; then
   /etc/ownscript.sh &
fi

# Try and synchronise time
#inettime=`cat /etc/enigma2/settings | grep systemoptions.inettime | cut -d "=" -f2`
# if [ ! $inettime ] && [ -e /sbin/ntpdate ]; then
if [ -e /sbin/ntpdate ]; then
   echo "Set internet time"
   /sbin/ntpdate de.pool.ntp.org
   /bin/fp_control -sst &
else
   if [ -e /usr/sbin/time.sh ]; then
      echo "Use transponder time"
      /usr/sbin/time.sh &
   fi
fi

#   stfbcontrol a 255

echo "Loading E2" > /dev/vfd
echo "Loading E2"

until false
do
   echo "Entering e2 main loop"
   if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
      showiframe -p /usr/local/share/enigma2/backdrop.mvi &
   fi
   /usr/local/bin/enigma2
   rtv=$?
   echo "e2 ended <- RTV: " $rtv
   /bin/fp_control -i 40 0
   case "$rtv" in
      0) echo "E2 ERROR"
         echo "E2 Error" > /dev/vfd
         init 6;;
      1) echo "SHUTDOWN"
         echo "Shutdown" > /dev/vfd
         if [ -e /usr/local/share/enigma2/shutdown.mvi ]; then
            showiframe -p /usr/local/share/enigma2/shutdown.mvi &
         fi
         init 0;;
      2) echo "REBOOT"
         echo "Reboot" > /dev/vfd
         init 6;;
      3) echo "E2 RESTART"
         echo "Restart GUI" > /dev/vfd
         echo "0" > /proc/progress
         showiframe -p /boot/bootlogo.mvi &;;
      *) echo "ERROR"
         init 6;;
   esac
done

#never reached
echo "Reboot FS9000/9200" > /dev/vfd
echo "Reboot FS9000/9200"
reboot

