#!/bin/sh
#Version 140727.1

echo "Fortis HS8200"

MODDIR=/lib/modules

echo "Init frontpanel"
insmod $MODDIR/nuvoton.ko
insmod $MODDIR/simu_button.ko

if [ -e /var/etc/.firstboot ]; then
   echo "WAIT 1 min" >/dev/vfd
   echo "WAIT 1 minute"
   rm /var/etc/.firstboot
   sleep 1
   touch /dev/.devfsd
else
   echo "LOAD 10" >/dev/vfd
   echo "Start (LOAD 10)"
fi

if [ -d /dev/sda1/Recordings ]; then
   fsck.jfs -a /dev/sda1
fi

/etc/init.d/mountvirtfs start
/etc/init.d/portmap start

insmod $MODDIR/e2_proc.ko
#insmod $MODDIR/sata.ko

# Start automounter with umount timeout of 5 seconds
/etc/init.d/autofs start

echo "Starting DEBUG Interface"
/etc/init.d/mountall start
/etc/init.d/hostname start

echo -n "Starting telnetd "
autologin=`cat /etc/enigma2/settings | grep systemoptions.autologin | cut -d "=" -f2`
if [ ! $autologin ]; then
   /usr/sbin/telnetd -l /bin/autologin
   echo "with autologin"
else
   /usr/sbin/telnetd -l /bin/login
   echo "with normal login"
fi

echo "Init stmfb (LOAD 9)"
echo "LOAD 9" > /dev/vfd
insmod $MODDIR/stmcore-display-sti7105.ko

#insmod $MODDIR/stmfb.ko display0=1280x720-32@50:15m:pal:yuv:yuv;# display1=720x576-16@50:1m:pal:cvbs;
if grep -q "config.av.videoport=Scart" /etc/enigma2/settings; then
   insmod $MODDIR/stmfb.ko display0=720x576i-32@50:15m:pal:rgb:rgb; #SCART
else
   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:15m:pal:rgb:rgb; #HDMI
fi

echo "Loading modules"

if [ ! -e /boot/audio.elf ]; then
   echo "NO AUDIO FW!!!"
   "FW MISSING!!!" > /dev/vfd
fi

echo "Load audio firmware (LOAD 8)"
echo "LOAD 8" > /dev/vfd
dtsdown=`cat /etc/enigma2/settings | grep systemoptions.dtsdownmix | cut -d "=" -f2`
if [ ! $dtsdown ] && [ -e /boot/audio_dts.elf ]; then
   /bin/ustslave /dev/st231-1 /boot/audio_dts.elf > /dev/null
else
   /bin/ustslave /dev/st231-1 /boot/audio.elf > /dev/null
fi

echo "Load video firmware (LOAD 7)"
echo "LOAD 7" > /dev/vfd
/bin/ustslave /dev/st231-0 /boot/video.elf > /dev/null

echo "Init embx (LOAD 6)"
echo "LOAD 6" > /dev/vfd
insmod $MODDIR/embxshell.ko
insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
insmod $MODDIR/mme_host.ko transport0=shm

echo "Init AVS (LOAD 5)"
echo "LOAD 5" > /dev/vfd
insmod $MODDIR/avs.ko type=stv6418

player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
echo "Init player $player (LOAD 4)"
echo "LOAD 4" > /dev/vfd

insmod $MODDIR/mmelog.ko
insmod $MODDIR/ksound.ko
insmod $MODDIR/p2div64.ko
insmod $MODDIR/stm_v4l2.ko

insmod $MODDIR/pseudocard.ko

insmod $MODDIR/frontend_platform.ko
insmod $MODDIR/socket.ko
insmod $MODDIR/lnbh221.ko
insmod $MODDIR/lnb_pio.ko
insmod $MODDIR/avl2108.ko
#insmod $MODDIR/tda10024.ko

insmod $MODDIR/starci.ko

if [ $player -gt 131 ]; then
#   insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
#   if [ $?=='2' ]; then
#      # Simple pti
      insmod $MODDIR/pti.ko
#   fi
   insmod $MODDIR/stm_monitor.ko
   insmod $MODDIR/stmsysfs.ko
   insmod $MODDIR/stmdvb.ko
else
   insmod $MODDIR/pti.ko
   insmod $MODDIR/stmdvb.ko
   insmod $MODDIR/stm_monitor.ko
fi

echo "Init player2 (LOAD 3)"
echo "LOAD 3" > /dev/vfd
insmod $MODDIR/player2.ko
insmod $MODDIR/sth264pp.ko
insmod $MODDIR/stmalloc.ko
insmod $MODDIR/platform.ko
insmod $MODDIR/silencegen.ko

echo "Init HDMI-CEC"
if [ -e $MODDIR/cec.ko ];then
   insmod $MODDIR/cec.ko activemode=1
fi

insmod $MODDIR/bpamem.ko
mknod /dev/bpamem c 153 0

showiframe -p /boot/bootlogo.mvi &
stfbcontrol a 0

echo "Init lircd (LOAD 2)"
echo "LOAD 2" > /dev/vfd
mknod /dev/rc c 147 1 

/bin/evremote2 10 140 &

stfbcontrol a 255

# Why is this done twice?
#/etc/init.d/mountall start
#/etc/init.d/hostname start
#echo -n "Starting telnetd "
#autologin=`cat /etc/enigma2/settings | grep systemoptions.autologin | cut -d "=" -f2`
#if [ ! $autologin ]; then
#   /usr/sbin/telnetd -l /bin/autologin
#   echo "with autologin"
#else
#  /usr/sbin/telnetd -l /bin/login
#  echo "with normal login"
#fi
#end twice

wlan=`cat /etc/enigma2/settings | grep systemoptions.wlan | cut -d "=" -f2`
if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
   echo "No WLAN"
else
   insmod $MODDIR/$wlan.ko
   echo "$wlan WLAN"
#   echo "$wlan WLAN" > /dev/vfd
#   sleep 3
fi

if [ -e $MODDIR/ntfs.ko ]; then
   insmod $MODDIR/ntfs.ko
fi

if [ -e $MODDIR/cifs.ko ]; then
   insmod $MODDIR/cifs.ko
fi

echo "Init ftp (LOAD 1)"
echo "LOAD 1" >/dev/vfd
/etc/init.d/vsftpd start
/usr/sbin/inetd

NFS=`grep -c nfs /proc/cmdline`
if [ "$NFS" -eq "1" ]; then
   echo "Booting from nfs, don't set network"
else
   if [ -e /etc/network/interfaces ]; then
      ip addr flush eth0
      /etc/init.d/networking stop
      DHCP=`grep -c dhcp /etc/network/interfaces`
      if [ "$DHCP" -eq "1" ]; then
         echo "Starting DHCP"
         /etc/init.d/udhcpc start
      fi
      /etc/init.d/networking start
   fi
fi

# Handle SWAPPART and RECORD labels and USB devices
if [ -e /usr/sbin/amount.sh ]; then
   (sleep 20; /usr/sbin/amount.sh) &
fi

# inadyn
inadyn=`cat /etc/enigma2/settings | grep systemoptions.inadyn | cut -d "=" -f2`
if [ ! $inadyn ] ||  [ ! -e /usr/bin/inadyn ]; then
   echo "No inadyn"
else
   if [ -e /usr/bin/inadyn ]; then
      /usr/bin/inadyn &
#   else
#      echo "INADYN MISSING" > /dev/vfd
#      sleep 2
   fi
fi

# OpenSSh daemon
openssh=`cat /etc/enigma2/settings | grep systemoptions.openssh | cut -d "=" -f2`
if [ ! $openssh ] || [ ! -e /etc/init.d/sshd ]; then
   echo "No OpenSSH"
else
   if [ -e /etc/init.d/sshd ]; then
      (sleep 30; /etc/init.d/sshd start) &
#   else
#      echo "SSHD MISSING" > /dev/vfd
#      sleep 2
   fi
fi

# Enable PKT plugins
if [ ! -e /tmp/reference.dat ] && [ -e /var/bin/reference.dat ]; then
   cp /var/bin/reference.dat /tmp
fi

# Do own extras
if [ -e /etc/ownscript.sh ]; then
   /etc/ownscript.sh &
fi

#timefix e2
date -s "201406011200"
# Try and synchronise time
inettime=`cat /etc/enigma2/settings | grep systemoptions.inettime | cut -d "=" -f2`
if [ ! $inettime ] && [ -e /sbin/ntpdate ]; then
   echo "Set internet time"
#   (/sbin/ntpdate pl.pool.ntp.org; /bin/fp_control -s `date +"%H:%M:%S %d-%m-%Y"`) &
   (/sbin/ntpdate nl.pool.ntp.org; /bin/fp_control -s `date +"%H:%M:%S %d-%m-%Y"`) &
else
   if [ -e /usr/sbin/time.sh ]; then
      echo "Use transponder time"
      /usr/sbin/time.sh &
   fi
fi

echo "Start OpenPLi" > /dev/vfd
echo "Start OpenPLi"
until false
do
   echo "Entering e2 main loop"
   if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
      showiframe -p /usr/local/share/enigma2/backdrop.mvi
   fi
   /usr/local/bin/enigma2
   rtv=$?
   echo "e2 ended <- RTV: " $rtv
   case "$rtv" in
      0) echo "0"
         echo "E2 ERROR"
         echo "E2 Error" > /dev/vfd
         init 6;;
      1) echo "1"
         echo "SHUTDOWN"
         echo "Shutdown" > /dev/vfd
         init 0;;
      2) echo "2"
         echo "REBOOT"
         echo "Reboot" > /dev/vfd
         init 6;;
      3) echo "3"
         echo "RESTART GUI"
         echo "Restart GUI" > /dev/vfd
         echo "0" > /proc/progress
         if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
            showiframe -p /usr/local/share/enigma2/backdrop.mvi &
         else
            showiframe -p /boot/bootlogo.mvi &
         fi
         echo -n " ";;
      *) echo "*"
         echo "ERROR"
         echo "ERROR" > /dev/vfd
         init 6;;
   esac
done

#never reached
echo "REBOOT HS8200" > /dev/vfd
echo "REBOOT HS8200"
reboot -f
